bind = CTRL ALT, T, exec, ghostty
bind = SUPER, M, exec, command -v hyprshutdown >/dev/null 2>&1 && hyprshutdown || hyprctl dispatch exit
bind = SUPER, E, exec, nautilus
bind = SUPER, C, exec, gnome-calculator
bind = ALT, Space, exec, ~/.config/rofi/scripts/launcher_t2
bind = , PRINT, exec, hyprshot -m region
bind = CTRL ALT, Q, exec, hyprlock & sleep 1 && hyprctl dispatch dpms off
